-- ============================================================
-- Brazilian E-Commerce Olist Analysis
-- Database Schema (Oracle)
-- Extracted via DBMS_METADATA.GET_DDL from PROJECT_USER
-- ============================================================

-- 1. CATEGORY_TRASLATION
CREATE TABLE CATEGORY_TRASLATION (
    PRODUCT_CATEGORY_NAME         VARCHAR2(100),
    PRODUCT_CATEGORY_NAME_ENGLISH VARCHAR2(100),
    CONSTRAINT PK_CATEGORY_TRASLATION PRIMARY KEY (PRODUCT_CATEGORY_NAME)
);

-- 2. CUSTOMERS
CREATE TABLE CUSTOMERS (
    CUSTOMER_ID              VARCHAR2(50),
    CUSTOMER_UNIQUE_ID       VARCHAR2(50),
    CUSTOMER_ZIP_CODE_PREFIX NUMBER,
    CUSTOMER_CITY            VARCHAR2(100),
    CUSTOMER_STATE           VARCHAR2(10),
    CONSTRAINT PK_CUSTOMERS PRIMARY KEY (CUSTOMER_ID)
);

-- 3. SELLERS
CREATE TABLE SELLERS (
    SELLER_ID              VARCHAR2(50),
    SELLER_ZIP_CODE_PREFIX NUMBER,
    SELLER_CITY            VARCHAR2(100),
    SELLER_STATE           VARCHAR2(10),
    CONSTRAINT PK_SELLERS PRIMARY KEY (SELLER_ID)
);

-- 4. PRODUCTS
CREATE TABLE PRODUCTS (
    PRODUCT_ID                 VARCHAR2(50),
    PRODUCT_CATEGORY_NAME      VARCHAR2(100),
    PRODUCT_NAME_LANGTH        NUMBER,
    PRODUCT_DESCRIPTION_LANGTH NUMBER,
    PRODUCT_PHOTOS_QTY         NUMBER,
    PRODUCT_WEIGHT_G           NUMBER,
    PRODUCT_LENGHT_CM          NUMBER,
    PRODUCT_HEIGHT_CM          NUMBER,
    PRODUCT_WIDTH_CM           NUMBER,
    CONSTRAINT PK_PRODUCTS PRIMARY KEY (PRODUCT_ID)
);

-- 5. GEOLOCATION
CREATE TABLE GEOLOCATION (
    GEOLOCATION_ZIP_CODE_PREFIX NUMBER,
    GEOLOCATION_LAT              NUMBER(12,8),
    GEOLOCATION_LNG              NUMBER(12,8),
    GEOLOCATION_CITY             VARCHAR2(100),
    GEOLOCATION_STATE            VARCHAR2(10)
);

-- 6. ORDERS
CREATE TABLE ORDERS (
    ORDER_ID                      VARCHAR2(50),
    CUSTOMER_ID                   VARCHAR2(50) NOT NULL,
    ORDER_STATUS                  VARCHAR2(30),
    ORDER_PURCHASE_TIMESTAMP      TIMESTAMP(6),
    ORDER_APPROVED_AT             TIMESTAMP(6),
    ORDER_DELIVERED_CARRIER_DATE  TIMESTAMP(6),
    ORDER_DELIVERED_CUSTOMER_DATE TIMESTAMP(6),
    ORDER_ESTIMATED_DELIVERY_DATE TIMESTAMP(6),
    CONSTRAINT PK_ORDERS PRIMARY KEY (ORDER_ID),
    CONSTRAINT FK_ORDER_CUSTOMER FOREIGN KEY (CUSTOMER_ID)
        REFERENCES CUSTOMERS (CUSTOMER_ID)
);

-- 7. ORDER_ITEMS
CREATE TABLE ORDER_ITEMS (
    ORDER_ID            VARCHAR2(50),
    ORDER_ITEM_ID        NUMBER,
    PRODUCT_ID           VARCHAR2(50),
    SELLER_ID            VARCHAR2(50),
    SHIPPING_LIMIT_DATE  TIMESTAMP(6),
    PRICE                NUMBER(10,2),
    FREIGHT_VALUE        NUMBER(10,2),
    CONSTRAINT PK_ORDER_ITEMS PRIMARY KEY (ORDER_ID, ORDER_ITEM_ID),
    CONSTRAINT FK_OI_ORDER   FOREIGN KEY (ORDER_ID)   REFERENCES ORDERS (ORDER_ID),
    CONSTRAINT FK_OI_PRODUCT FOREIGN KEY (PRODUCT_ID) REFERENCES PRODUCTS (PRODUCT_ID),
    CONSTRAINT FK_OI_SELLER  FOREIGN KEY (SELLER_ID)  REFERENCES SELLERS (SELLER_ID)
);

-- 8. ORDER_PAYMENTS
CREATE TABLE ORDER_PAYMENTS (
    ORDER_ID             VARCHAR2(50),
    PAYMENT_SEQUENTIAL   NUMBER,
    PAYMENT_TYPE         VARCHAR2(30),
    PAYMENT_INSTALLMENTS NUMBER,
    PAYMENT_VALUE        NUMBER(10,2),
    CONSTRAINT PK_ORDER_PAYMENTS PRIMARY KEY (ORDER_ID, PAYMENT_SEQUENTIAL),
    CONSTRAINT FK_OP_ORDER FOREIGN KEY (ORDER_ID) REFERENCES ORDERS (ORDER_ID)
);

-- 9. ORDER_REVIEWS
CREATE TABLE ORDER_REVIEWS (
    REVIEW_ID               VARCHAR2(50),
    ORDER_ID                VARCHAR2(50),
    REVIEW_SCORE             NUMBER,
    REVIEW_COMMENT_TITLE     VARCHAR2(200),
    REVIEW_COMMENT_MESSAGE   VARCHAR2(2000),
    REVIEW_CREATION_DATE     TIMESTAMP(6),
    REVIEW_ANSWER_TIMESTAMP  TIMESTAMP(6),
    CONSTRAINT PK_ORDER_REVIEWS PRIMARY KEY (REVIEW_ID),
    CONSTRAINT FK_OR_ORDER FOREIGN KEY (ORDER_ID) REFERENCES ORDERS (ORDER_ID)
);
